### ISSUE TITLE
Export option - re-order checkbox

### ISSUE THREAD

**Issue by boekhoffm** [coolsoft-ita/autopintab#16]
It appears that the "Export" option does not export the "Reorder pinned tabs using pattern" value (true|false)

Still it's an excellent add-in!

**Comment by nicorac** [comment]
Well, in fact the bug is worst then that: that option is also not restored at FF restart, so it's always `false`.
I've never noticed it because I'm not using it (and left it to `false`), but still wondering how this bug could have been around for more than 2 years 🙄.

I've just published an update (v1.3.3) on [Mozilla Addons Page](https://addons.mozilla.org/firefox/addon/autopintab/).
Thanks for reporting it 👍
