### ISSUE TITLE
stop the spring of new tab before pinning it

### ISSUE THREAD

**Issue by seasaltseasalt** [coolsoft-ita/autopintab#2]
Hello: great addon! Thankyou. Would be great if we could stop the new tab opening at end of open tabs (it is like the new tab springs over to right hand side) then jumps back and is pinned (over on left hand side). I find it a bit dizzy-ing.  Would be smoother to remove this spring action.

**Comment by nicorac** [comment]
Sadly this is not possible: web xtensions are informed of tab open only **after** the tab has been opened.

This was the API status at the time I started writing the web extension; it could have changed meanwhile, will have a look ;)

**Comment by nicorac** [comment]
I confirm that it's actually not possible to intercept the creation of a "standard" tab and immediately pin it.

The first event raised upon tab creation is onCreated (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onCreated), but it can't be used since tab URL is not yet set at the time the event is raised.

From Mozilla docs:
> Note that the tab's URL may not be given its final value at the time this event fired. In particular, Firefox opens a new tab with the URL "about:blank" before loading the new page into it. You can listen to tabs.onUpdated events to be notified when a URL is set.

Since we need the URL being set to apply pattern rules, the first usable event is onUpdated, which is the one currently in use, and happens **after** the tab has been shown (unpinned).
