### ISSUE TITLE
Bug: Unreadable text in configuration box with dark theme

### ISSUE THREAD

**Issue by Luctins** [coolsoft-ita/autopintab#7]
The pattern input box is unreadable with dark themes, probably because it's color is not dependent on the current theme.
this isn't caused by addons, such as Dark Reader because it's a protected page.
Screenshot:
![Screenshot from 2019-11-24 15-06-46](https://user-images.githubusercontent.com/4743486/69498988-a3a77780-0ecc-11ea-85bb-2161c02cb603.png)

**Comment by nicorac** [comment]
Was trying to reproduce the bug on my side, but I had some difficulties: once enabled the default "Dark theme", my FF Options pages were still... light :confused:

When looking for how to enable the dark mode to the whole browser I've found instructions about setting this configuration option:
- `browser.in-content.dark-mode = true`

Well, this is not enough, because it requires that you have dark mode enabled in Windows 10 too.
If you don't, then you also need to set (or create) this additional option:
- `ui.systemUsesDarkTheme = 1` (create if missing)

Now FF is fully dark, including Options and Additional components pages.
Just posting here the steps I've followed, hope they'll be useful to others...

Will now have a look at this bug :wink:

**Comment by nicorac** [comment]
Fixed in master branch (commit 8c387de9b8568ecf0b57166176b4f671fd05bad8).
Could you please check it out and confirm if everything works as expected on your side too?

PS: to test the extensions from sources please read the **Installation** section of [README.md](https://github.com/coolsoft-ita/autopintab/blob/master/README.md).

**Comment by Luctins** [comment]
I'll test it as soon as possible.
Thanks for the effort.

**Comment by Luctins** [comment]
I've tested the latest update, and it solved the problem
![Screenshot from 2019-11-27 13-45-55](https://user-images.githubusercontent.com/4743486/69742970-676a5600-111c-11ea-97ee-fb0d66d2ba14.png)
Thanks!

**Comment by Luctins** [comment]
How long usually does it take to push changes to the official channel?

**Comment by nicorac** [comment]
It usually takes no more than a couple of days 😉

**Comment by nicorac** [comment]
Update to version 1.1.1 is now available:
https://addons.mozilla.org/en-US/firefox/addon/autopintab/

(approval was really fast, thanks FF guys 👏)
